### ISSUE TITLE
bug commission-rate

### ISSUE THREAD

**Issue by sienrik15** [CosmosContracts/bounties#11]
I changed the commission-rate less than 5% in testnet and maybe stargaze has the same bug, i have a fix.
https://uni.juno.omniflix.co/
![image](https://user-images.githubusercontent.com/14026704/150821699-24fa9ddb-db20-4a17-80b5-366129e8182c.png)

EnrikeSam#9005

**Comment by JakeHartnell** [comment]
Can you provide details on how you achieved this to `Meow Stargaze ✨🔭#1736` or `dimi 🦙#2998` on the [Juno Discord](https://discord.gg/QcWPfK4gJ2)?
