### ISSUE TITLE
Band protocol IBC Challenge

### ISSUE THREAD

**Issue by vuong177** [CosmosContracts/bounties#13]
#### What me and Vinh did:
- Create a local bainchain, include data source, data script, v.v.  Just change length used in validation of port identifiers to 128 to create ibc channel from juno contract to bandchain.  My bandchain code [here](https://github.com/nguyenvuong1122000/chain)
- Create a Ibc channel from juno mainet to my local bandchain (I can't use band mainet because they don't approve wasm port, they still use ibc v1.1.5,  length used in validation of port identifiers still 64)
- I tried use laozi-testnet, but it have this error, it's reason i used local testnet
![image](https://user-images.githubusercontent.com/56973102/152646126-be68ffad-a8b2-4fac-86ba-3f36acac765b.png)

- Create a smart-contract for request oracle data over IBC. Smart contract code [here](https://github.com/notional-labs/oracle-ibc/tree/main/contracts). I've store it in Juno mainnet (code_id = 52)
-  Call contract to query oracle data over IBC and received oracle data.
-  deployment guide here: [Guide](https://github.com/notional-labs/oracle-ibc/blob/main/DeploymentGuide.md)

### Proof: Tx ibc-received in mintscan:
- Call contract : https://www.mintscan.io/juno/txs/E9F4F8C7AA3F8D287D8C199540CF90E25E6A459A8A49E5ACF78FEF93CD7DAB1F
- Ibc packet received in Juno mainnet : https://www.mintscan.io/juno/txs/0419C27A42844342E56EA82C70D44611E3A2D299808BD523220CD61BDE619778

**Comment by nghuyenthevinh2000** [comment]
@JakeHartnell 
pls have a look, sir

**Comment by JakeHartnell** [comment]
Repo doesn't seem to be public: https://github.com/notional-labs/oracle-ibc/tree/main/contracts

Could you submit a PR to band protocol to start discussion? They need to upgrade their IBC version, would love to use their oracles in contracts. CC @faddat.

**Comment by nghuyenthevinh2000** [comment]
oh sorry, I just change visibility to public

about band, I have already submitted a pr to their reo but they didn't answer yet: https://github.com/bandprotocol/chain/issues/202

**Comment by nghuyenthevinh2000** [comment]
here is the pr to start discussion:
https://github.com/bandprotocol/chain/pull/205

**Comment by nghuyenthevinh2000** [comment]
here is the pr discussion on ibc upgrade:
https://github.com/bandprotocol/chain/pull/205

**Comment by nguyenvuong1122000** [comment]
@JakeHartnell, can you take a look at our solution

**Comment by blockcreators** [comment]
The band channel is created right @faddat 

Do you mind sharing the ID for it again? Thanks!

**Comment by the-frey** [comment]
I think we're waiting on band to commit to an IBC version bump?

**Comment by nguyenvuong1122000** [comment]
@the-frey yes. Band mainnet is using ibc v1.1.5. It don't allow wasm port.

**Comment by JakeHartnell** [comment]
We need to pressure them to upgrade or we should launch a better oracle solution.

**Comment by vuong177** [comment]
Is this bounty still available? Bandprotocol has upgraded their testnet to ibc v3 and we can enable ibc with wasm port on it.

**Comment by JakeHartnell** [comment]
> Is this bounty still available? Bandprotocol has upgraded their testnet to ibc v3 and we can enable ibc with wasm port on it.

Go for it!
