### ISSUE TITLE
Question about bounties 2 and 3

### ISSUE THREAD

**Issue by romelukaku** [CosmosContracts/bounties#6]
Trade over IBC means to IBC transfer smart contract tokens via IBC from juno to osmosis, then do swap transaction on osmosis, then IBC transfer back to juno
Or 
make custom ibc app so that we can have an ibc transaction to do all of the above at once

Similar question for bounty 3

**Comment by JakeHartnell** [comment]
> make custom ibc app so that we can have an ibc transaction to do all of the above at once

This. Much cleaner.
